version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always  
    ports:
      - "3001:3000"
    volumes:
      - .:/app  
      - /app/node_modules
    command: npm run start:dev  
         

